version: '3'

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./html/default.conf:/etc/nginx/conf.d/default.conf

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web-server
